name: Build CI

on:
  push:
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y lld clang llvm uuid-dev liblzma-dev mingw-w64 zip

    - name: Setup Variables
      run: |
        echo "NDK_PATH=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV

    - name: Build Toolkits
      run: |
        make target_toolkit_linux
        make target_toolkit_windows
      
    - name: Build Magisk Module
      run: |
        make target_magisk_module

    - name: Unpack artifacts
      run: |
        mkdir -p artifacts/toolkit_linux artifacts/toolkit_windows artifacts/magisk_module
        unzip targets/toolkit_linux/build/toolkit_linux.zip -d artifacts/toolkit_linux
        unzip targets/toolkit_windows/build/toolkit_windows.zip -d artifacts/toolkit_windows
        unzip targets/magisk_module/build/module_android.zip -d artifacts/magisk_module

    - name: Upload Linux Toolkit
      uses: actions/upload-artifact@v4
      with:
        name: toolkit_linux
        path: artifacts/toolkit_linux/*

    - name: Upload Windows Toolkit
      uses: actions/upload-artifact@v4
      with:
        name: toolkit_windows
        path: artifacts/toolkit_windows/*

    - name: Upload Magisk Module
      uses: actions/upload-artifact@v4
      with:
        name: magisk_module
        path: artifacts/magisk_module/*
